/**
 *
 * Package inizialmente recuperato da [https://code.google.com/p/e3roid/](https://code.google.com/p/e3roid/)
 * Serve a caricare le mappe tmx, generate da Tiled, programma opensource per la generazione delle tiles.
 *
 *
 *
 *
 */
package com.abubusoft.xenon.mesh.tiledmaps

import com.abubusoft.xenon.mesh.tiledmaps.internal.AbstractLayerHandler.onBuildView
import com.abubusoft.xenon.mesh.MeshFactory.createSprite
import com.abubusoft.xenon.mesh.modifiers.TextureQuadModifier.setTextureCoords
import com.abubusoft.xenon.texture.AtlasTextureOptions.tileWidth
import com.abubusoft.xenon.texture.AtlasTextureOptions.tileHeight
import com.abubusoft.xenon.texture.AtlasTextureOptions.margin
import com.abubusoft.xenon.texture.AtlasTextureOptions.spacing
import com.abubusoft.xenon.mesh.tiledmaps.internal.AbstractLayerHandler.view
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.SAXUtil.getString
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.SAXUtil.getInt
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.SAXUtil.getFloat
import com.abubusoft.xenon.mesh.tiledmaps.internal.MapHandler.buildTiledLayerHandler
import com.abubusoft.xenon.mesh.tiledmaps.internal.MapHandler.buildImageLayerHandler
import com.abubusoft.xenon.mesh.tiledmaps.internal.MapHandler.buildObjectLayerHandler
import com.abubusoft.xenon.math.XenonMath.clamp
import com.abubusoft.xenon.mesh.tiledmaps.internal.TiledLayerHandler.onBuildView
import com.abubusoft.xenon.texture.AtlasTexture.selectedCurrentFrame
import com.abubusoft.xenon.texture.AtlasTexture.coordStartY
import com.abubusoft.xenon.texture.AtlasTexture.coordEndY
import com.abubusoft.xenon.texture.AtlasTexture.coordStartX
import com.abubusoft.xenon.texture.AtlasTexture.coordEndX
import com.abubusoft.xenon.mesh.tiledmaps.internal.MapHandler.onBuildView
import com.abubusoft.xenon.mesh.tiledmaps.internal.MapHandler.buildMapController
import com.abubusoft.xenon.mesh.MeshFactory.createTiledGrid
import com.abubusoft.xenon.math.Point2.setCoords
import com.abubusoft.xenon.core.util.ResourceUtility.resolveAddress
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.TMXLoaderHandler.load
import com.abubusoft.xenon.mesh.MeshFactory.createTile
import com.abubusoft.xenon.mesh.tiledmaps.TiledMap
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.TMXLoaderType
import com.abubusoft.xenon.texture.TextureFilterType
import com.abubusoft.xenon.mesh.tiledmaps.Layer.LayerType
import com.abubusoft.xenon.texture.TextureOptions
import com.abubusoft.xenon.mesh.tiledmaps.ImageLayer.FillModeType
import com.abubusoft.xenon.mesh.tiledmaps.internal.TiledMapView
import com.abubusoft.xenon.mesh.MeshFactory
import com.abubusoft.xenon.mesh.MeshOptions
import com.abubusoft.xenon.vbo.BufferAllocationOptions
import com.abubusoft.xenon.vbo.BufferAllocationType
import com.abubusoft.xenon.mesh.modifiers.TextureQuadModifier
import com.abubusoft.xenon.mesh.MeshSprite
import com.abubusoft.xenon.mesh.tiledmaps.internal.ImageLayerHandler
import com.abubusoft.xenon.texture.TextureRepeatType
import com.abubusoft.xenon.texture.TextureManager
import com.abubusoft.xenon.core.XenonRuntimeException
import com.abubusoft.xenon.texture.AtlasTextureOptions
import com.abubusoft.xenon.texture.AtlasTexture
import com.abubusoft.xenon.mesh.tiledmaps.internal.AbstractLayerHandler
import com.abubusoft.xenon.mesh.tiledmaps.internal.LayerDrawer
import com.abubusoft.xenon.mesh.tiledmaps.PropertiesCollector
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.TMXPredefinedProperties
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.SAXUtil
import com.abubusoft.xenon.mesh.tiledmaps.tmx.LayerAttributes
import com.abubusoft.xenon.mesh.tiledmaps.TiledLayer
import com.abubusoft.xenon.mesh.tiledmaps.ImageLayer
import com.abubusoft.xenon.mesh.tiledmaps.ObjectLayer
import com.abubusoft.xenon.math.XenonMath
import com.abubusoft.xenon.mesh.tiledmaps.internal.MapHandler
import com.abubusoft.xenon.mesh.tiledmaps.orthogonal.OrthogonalMapHandler
import com.abubusoft.xenon.mesh.tiledmaps.isometric.IsometricMapHandler
import com.abubusoft.xenon.mesh.tiledmaps.isostaggered.ISSMapHandler
import com.abubusoft.xenon.mesh.tiledmaps.ScrollDirectionType
import com.abubusoft.xenon.mesh.tiledmaps.MovementListenerOptions
import com.abubusoft.xenon.mesh.tiledmaps.ObjBase.CategoryType
import com.abubusoft.xenon.mesh.tiledmaps.ObjBase
import com.abubusoft.xenon.mesh.tiledmaps.ObjDefinition
import com.abubusoft.xenon.mesh.tiledmaps.ObjectLayerDrawer
import com.abubusoft.xenon.mesh.tiledmaps.internal.ObjectLayerHandler
import com.abubusoft.xenon.math.Matrix4x4
import com.abubusoft.xenon.mesh.tiledmaps.ObjClass
import com.abubusoft.xenon.mesh.tiledmaps.ObjInstance
import com.abubusoft.xenon.entity.SpriteEntity
import com.abubusoft.xenon.mesh.tiledmaps.ObjSprite
import com.abubusoft.kripton.annotation.BindType
import kotlin.jvm.JvmOverloads
import com.abubusoft.xenon.texture.TextureRegion
import com.abubusoft.xenon.mesh.tiledmaps.TileAnimationFrame
import com.abubusoft.xenon.mesh.tiledmaps.internal.TiledLayerHandler
import android.annotation.SuppressLint
import com.abubusoft.xenon.shader.ShaderTiledMap
import com.abubusoft.xenon.mesh.tiledmaps.MapOrientationType
import com.abubusoft.xenon.math.Point2
import com.abubusoft.xenon.mesh.tiledmaps.TileAnimation
import com.abubusoft.xenon.mesh.tiledmaps.TileSet
import android.util.SparseIntArray
import com.abubusoft.xenon.mesh.MeshGrid
import com.abubusoft.xenon.mesh.tiledmaps.MovementListener
import com.abubusoft.xenon.mesh.tiledmaps.modelcontrollers.MapController
import com.abubusoft.xenon.mesh.MeshTile
import com.abubusoft.xenon.mesh.tiledmaps.TileProperty
import com.abubusoft.xenon.mesh.tiledmaps.TiledMapOptions
import com.abubusoft.xenon.mesh.tiledmaps.tmx.MapAttributes
import com.abubusoft.xenon.mesh.tiledmaps.TiledMapPositionType
import com.abubusoft.xenon.shader.ShaderManager
import com.abubusoft.xenon.shader.ArgonShaderOptions
import kotlin.Throws
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.TMXException
import com.abubusoft.xenon.core.util.ResourceUtility
import com.abubusoft.xenon.mesh.tiledmaps.TiledMapFactory
import com.abubusoft.xenon.mesh.tiledmaps.tmx.loader.TMXLoaderHandler
import com.abubusoft.xenon.mesh.tiledmaps.TiledMapFillScreenType
import android.util.SparseArray
